#######################################datasource配置########################################################
spring:
  application:
    name: tongue-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/data_show?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
      username: root
      password: root
      # 初始化连接大小
      initial-size: 8
      # 最小空闲连接数
      min-idle: 5
      #最大连接数
      max-active: 10
      #查询超时时间
      query-timeout: 6000
      #事务查询超时时间
      transaction-query-timeout: 6000
      #关闭空闲连接超时时间
      remove-abandoned-timeout: 1800
      # 配置获取连接等待超时的时间
      max-wait: 60000
      ##配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      ##配置一个连接在池中最小生存的时间，单位是毫秒
      min-victable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      pool-prepared-statements: true
      max-open-prepared-statements: 300
      verify-server-certificate: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-dataSource-stat: true
      # StatViewServlet配置
      #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
      #是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #允许清空统计数据
        reset-enable: true
        login-username: admin
        login-password: 123
        #StatViewSerlvet展示出来的监控信息比较敏感，是系统运行的内部情况，如果你需要做访问控制，可以配置allow和deny这两个参数
        #deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
        #配置的格式
        #<IP>
        #或者<IP>/<SUB_NET_MASK_size>其中128.242.127.1/24
        #24表示，前面24位是子网掩码，比对的时候，前面24位相同就匹配,不支持IPV6。
        # allow: 127.0.0.1
        # deny: 128.242.127.1/24,128.242.128.1
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      # aop-patterns:
      connection-init-sqls: set names utf8mb4

#######################################系统配置########################################################
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        #include: bus-refresh
        include: "*"
  endpoint:
    health:
      show-details: always

# 系统日志保存目录
log_dir: /Users/Apple/Desktop/git/tongue-security-console/logs